### ISSUE TITLE
Build instructions for MacOS

### ISSUE THREAD

**Issue by codecowboy** [acrogenesis/macchanger#12]
Did you build this from the original macchanger for Linux? If so, Would you be able to post build instructions for macchanger so that I can build 1.7 on MacOS? I could then take over maintenance of this if you want. If I try to build from source I get:

`netinfo.c:32:10: fatal error: 'linux/ethtool.h' file not found`

How did you get around this?

**Comment by acrogenesis** [comment]
That's strange @codecowboy there's nothing to build in this package it's just a Ruby script. Perhaps you are trying to build this other tool https://github.com/alobbs/macchanger

**Comment by codecowboy** [comment]
Yep, apologies for the confusion and thanks for getting back to me :)
