### ISSUE TITLE
`macchanger -r` freezes

### ISSUE THREAD

**Issue by hexdump** [acrogenesis/macchanger#13]
when i try to randomize my MAC address, `macchanger` seems to freeze. after running `$ macchanger -r en0` and waiting for about ~30 seconds, no output is shown; hitting `^C` stops the program, giving the following error:

```
^C/usr/local/bin/macchanger:56:in `system': Interrupt
	from /usr/local/bin/macchanger:56:in `set'
	from /usr/local/bin/macchanger:48:in `random'
	from /usr/local/bin/macchanger:51:in `random'
	from /usr/local/bin/macchanger:51:in `random'
	from /usr/local/bin/macchanger:51:in `random'
	... (100s of lines of the same)
	from /usr/local/bin/macchanger:51:in `random'
	from /usr/local/bin/macchanger:63:in `start'
	from /usr/local/bin/macchanger:83:in `<main>'
```

i'm running macchanger `1.3.2` on macOS `10.14.6 (18G3005)`. i installed by running `brew install acrogenesis/macchanger/macchanger`.

**Comment by acrogenesis** [comment]
Hello @hexdump I've tried replicating this problem in 10.15.2 but it worked well.
Are you getting asked for your password? Is your en0 device turned on?

**Comment by hexdump** [comment]
ok, this is getting weird. i wasn't asked for my password yesterday and the day before, but i am getting asked for my password today. my `en0` device is turned on, and i can set its address manually with `-m`/`--mac`.

**Comment by acrogenesis** [comment]
So it's working now?

**Comment by hexdump** [comment]
no—still freezes.

**Comment by acrogenesis** [comment]
Which ruby version do you have? `ruby -v`

**Comment by jackall3n** [comment]
I am experiencing this as well. Ruby version is the same

**Comment by jackall3n** [comment]
@hexdump what OS version are you running? https://github.com/feross/SpoofMAC/issues/87#issuecomment-539864016

**Comment by hexdump** [comment]
i'm running macchanger `1.3.2` on `macOS 10.14.6 (18G3005)`.

**Comment by leomiglio02** [comment]
for me the problem was caused by ineutils that change the ifconfig path, in fact when macchanger call for ifconfig it is not in che /sbin/ifconfig but in a subdirectory of inetutils
if you do
`which ifconfig`
and it's inside a path like /usr/local/opt/inetutils/libexec/gnubin/ifconfig this is the error

I try to down my interface with
`sudo ifconfig en0 down`
and not work, but with
`sudo /sbin/ifconfig en0 down`
it  worked

**Comment by acrogenesis** [comment]
Thanks @leomiglio02 I've changed the default to `/sbin/ifconfig` https://github.com/acrogenesis/macchanger/commit/30c657b5ed9cbbb9ad7991801afbd08124b7cbbc
