### ISSUE TITLE
custom MAC address doesn't work sometime

### ISSUE THREAD

**Issue by sherbitfish** [acrogenesis/macchanger#14]
When I want to create a new custom MAC address like "11:22:33:44:55:66" it says "Try another mac address". Why am I not able to change it to that? Also, I tried a random MAC address generator like this [one](http://www.macvendorlookup.com/mac-address-generator) and non of them work. Why does this happen?

**Comment by acrogenesis** [comment]
Either it was related to #15 or it wasn't a valid mac.
