### ISSUE TITLE
Doesn't work on MacOS Monterey any more

### ISSUE THREAD

**Issue by D4v1dH03** [acrogenesis/macchanger#15]
It only shows infinite output of `ifconfig: ioctl (SIOCAIFADDR): Can't assign requested address` even if I specified a specific MAC address

**Comment by gy2256** [comment]
I have the same issue and the output is the same.

**Comment by acrogenesis** [comment]
Yeah, I've been researching why this is happening. Apple changed the way it worked in Monterey.

**Comment by githoniel** [comment]
same for me. It also do not work for wire network via type-c

```bash
sudo ifconfig {name} ether {mac}
```

always return `ifconfig: ioctl (SIOCAIFADDR): Can't assign requested address`

**Comment by dodas** [comment]
Did you guys try disconnecting from the wifi network before changing the mac address?

**Comment by acrogenesis** [comment]
@dodas that works, I'm updating the code to include a wifi disconnect

**Comment by weagley** [comment]
I'm seeing the same issue with macchanger 1.4.1.

I'm on a MacBook Pro (15-inch, 2019) on macOS 12.1

uname -a
Darwin quicksilver.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64



<img width="437" alt="image" src="https://user-images.githubusercontent.com/534148/153308123-8267dcbf-7810-4dff-a2c9-1eec0004b9fd.png">

**Comment by weagley** [comment]
never mind, was able to figure out this problem.

update for anyone facing the same issue with macOS 12.1 through 12.2.1 (the highest version as of this writing):

1. do not disable wifi entirely first. for example, DO NOT use `networksetup -setairportpower en0 off` #don't use this
2. instead, merely disconnect from all wi-fi networks. e.g. as of this writing, this works: `/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport "en0" -z` # use this

enjoy

**Comment by H3in0Wal13r** [comment]
that's work perfect for the wifi device but what if you use a usb network device. Here you got the same error. How must the commad look like to resolve the problem?
thank's for your reply
