### ISSUE TITLE
Working at command line but not reflected in properties

### ISSUE THREAD

**Issue by Quinnus** [acrogenesis/macchanger#17]
Noob here, please go easy on me....

Everything working perfectly:

macchanger -r en0
password requested
positive response with new MAC address (adapter turns off during change, have to manually reconnect)
Router flags a new device joining network
However under network properties the address for en0 hasn't changed

Should I see the new address reported in terminal reflected in the network properties window (i.e., option click network icon in menu bar)?.

Macbook Air M1
Monterey 12.2

Thanks.

**Comment by Quinnus** [comment]
Actually the router is recognising the new MAC address, so yeah all good!.

**Comment by acrogenesis** [comment]
Yeah under network properties you won't see the address change. You can check the current address with `macchanger -s en0`
