### ISSUE TITLE
"Device can't be blank"

### ISSUE THREAD

**Issue by mmathys** [acrogenesis/macchanger#2]
This error occurs when attempting to either show the mac address or set a random mac address:
```
/usr/local/bin/macchanger:74:in `<main>': Device can't be blank (ArgumentError)
```
Running OS X Yosemite 10.10.4

**Comment by acrogenesis** [comment]
You have to specify a device like this, `macchanger -s en0`

**Comment by acrogenesis** [comment]
If your Mac has an ethernet port it will be en0 and the wifi en1. If you only have wifi, the wifi will be en0

**Comment by mmathys** [comment]
thanks for your help, appreciate it!
