### ISSUE TITLE
not working?

### ISSUE THREAD

**Issue by ashyyv** [acrogenesis/macchanger#20]
i am able to change it and it even shows when i type ifconfig, i'm using this to bypass a wifi pause but when its "changed" its still knows its the same device? I don't know why this suddenly stopped working it was working really well just a few days ago

**Comment by acrogenesis** [comment]
You probably should also change the name your computer uses https://support.apple.com/guide/mac-help/change-computers-local-hostname-mac-mchlp2322/mac

**Comment by ashyyv** [comment]
Hey there, thanks for replying, it somehow started working again :)
