### ISSUE TITLE
mac change doesn't persist

### ISSUE THREAD

**Issue by penetrance** [acrogenesis/macchanger#5]
I tried changing the MAC of my wifi, which is en1, by using macchanger -r en1. The program tells me it's successful, but checking the MAC address of my wifi adapter in Network settings shows it still as the old MAC address. When I reboot, it goes back to the original MAC address. Is there a way to make the change persist?

I'm using OS X El Capitan 10.11 with homebrew. Thanks

**Comment by mmathys** [comment]
you can't do it directly with macchanger, but you could use Automator to run the startup command.

Follow [this guide](http://stackoverflow.com/questions/6442364/running-script-upon-login-mac/6445525#6445525) and paste your command `macchanger -r en1`. Hope this helps

**Comment by acrogenesis** [comment]
The MAC address on the wifi adapter will always show the real address. I'm using El Capitan and it's working great, if you want to be sure run `ifconfig en1`. Also as @mmathys to make the change persist you can run it as a startup command
