### ISSUE TITLE
Throws alot of errors, when wifi is down

### ISSUE THREAD

**Issue by TheDuchy** [acrogenesis/macchanger#7]
Macchanger spits out hundreds of lines of errors, when wifi is down. It would be nice, if you would include a condition that checks if it's down.

**Comment by acrogenesis** [comment]
It seems this method is causing a recursive error by calling itself again when it fails to set the maccaddress when the device is down. Will try and fix soon, or if you can please submit a PR

https://github.com/acrogenesis/macchanger/blob/200e8ca34cb235fefe573ce1a183be3a2e658c07/bin/macchanger#L46
